import uma_linha, documentando_funcoes, documentando_classes

print(dir(uma_linha))
print(uma_linha.__doc__)
print(uma_linha.__file__)
print(uma_linha.__name__)
help(uma_linha)
print('\n')
print(dir(documentando_funcoes))
print(documentando_funcoes.__doc__)
print(documentando_funcoes.__file__)
print(documentando_funcoes.__name__)
help(documentando_funcoes)
print('\n')
print(dir(documentando_funcoes))
print(documentando_funcoes.__doc__)
print(documentando_funcoes.__file__)
print(documentando_funcoes.__name__)
help(documentando_funcoes)
print('\n')
print(dir(documentando_classes))
print(documentando_classes.__doc__)
print(documentando_classes.__file__)
print(documentando_classes.__name__)
help(documentando_classes)